# Generated by Django 4.1.3 on 2022-11-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_generalconfigmodel_alter_projectmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconfigmodel',
            name='value',
            field=models.TextField(),
        ),
    ]
