# Generated by Django 4.1.3 on 2022-11-26 23:17

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_generalconfigmodel_value'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='generalconfigmodel',
            constraint=models.UniqueConstraint(fields=(django.db.models.functions.text.Lower('key'), django.db.models.functions.text.Lower('section')), name='key_section_contraint'),
        ),
    ]
